
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwtbzscwnqkogdviniro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "463184c6-bb14-4db5-8975-0a34be1087e9";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
